{* DO NOT EDIT THIS FILE! Use an override template instead. *}
{default attribute_base='ContentObjectAttribute' html_class='full'}

<p>Choose your newsletter subscriptions:</p>
<table class="list">
<tr><th class="tight"></th><th>Name</th><th>Status</th></tr>
{foreach $attribute.content.list as $list}
{*if or($list.node, $list.subscription)*}
{if and(ne($list.node.data_map.user_administration.content,'0'),or($list.node, $list.subscription))}
<tr><td><input type="checkbox" id="ezcoa-{if ne( $attribute_base, 'ContentObjectAttribute' )}{$attribute_base}-{/if}{$attribute.contentclassattribute_id}_{$attribute.contentclass_attribute_identifier}" 
{if $list.selected}
 checked
{/if}
{if $list.disabled}
 disabled 
{/if}

    name="{$attribute_base}_newsletterlist_selection{$attribute.id}[{$list.list.id}]" />
<input type="hidden"  name="{$attribute_base}_newsletterlist_avialable{$attribute.id}[]" value="{$list.list.id}" />
</td>
<td>{if $list.node}{$list.node.name|wash( xhtml )}{else}{$list.list.name|wash( xhtml )}{/if}</td>
{*
define( 'eZSubscription_StatusPending', 0 );
define( 'eZSubscription_StatusConfirmed', 1 );
define( 'eZSubscription_StatusApproved', 2 );
define( 'eZSubscription_StatusRemovedSelf', 3 );
define( 'eZSubscription_StatusRemovedAdmin', 4 );
*}
<td>
{if array(3,0)|contains($list.subscription.status)}
{'unsubscribed'|i18n( 'extension/newletteraddons' )}
{elseif array(2,1)|contains($list.subscription.status)}
{'subscribed'|i18n( 'extension/newletteraddons' )}
{elseif array(4)|contains($list.subscription.status)}
{'unsubscribed by admin'|i18n( 'extension/newletteraddons' )}
{else}
{'unsubscribed'|i18n( 'extension/newletteraddons' )}
{/if}
</td>
</tr>
{/if}
{/foreach}
</table>

        
{*<input id="ezcoa-{if ne( $attribute_base, 'ContentObjectAttribute' )}{$attribute_base}-{/if}{$attribute.contentclassattribute_id}_{$attribute.contentclass_attribute_identifier}" class="{eq( $html_class, 'half' )|choose( 'box', 'halfbox' )} ezcc-{$attribute.object.content_class.identifier} ezcca-{$attribute.object.content_class.identifier}_{$attribute.contentclass_attribute_identifier}" type="text" size="70" name="{$attribute_base}_ezstring_data_text_{$attribute.id}" value="{$attribute.data_text|wash( xhtml )}" />*}
{/default}

