{* DO NOT EDIT THIS FILE! Use an override template instead. *}
{* eZNewsletter - confirm remove newsletter type *}
<div class="context-block">

{* DESIGN: Header START *}<div class="box-header"><div class="box-tc"><div class="box-ml"><div class="box-mr"><div class="box-tl"><div class="box-tr">

<h1 class="context-title">{'Confirm newsletter removal'|i18n( 'design/eznewsletter/confirmremove_newslettertype' )}</h1>

{* DESIGN: Mainline *}<div class="header-mainline"></div>

{* DESIGN: Header END *}</div></div></div></div></div></div>

{* DESIGN: Content START *}<div class="box-ml"><div class="box-mr"><div class="box-content">

<div class="message-confirmation">

<h2>{'Are you sure you want to remove all the newsletters?'|i18n( 'design/eznewsletter/confirmremove_newslettertype' )}</h2>

<ul>
{if is_set($delete_result)}
{foreach $delete_result as $item}
    <li>{$item.name|wash}</li>
{/foreach}
{/if}
</ul>

<p><b>{'Warning'|i18n( 'design/eznewsletter/confirmremove_newslettertype' )}:</b></p>
<p>{'Do not proceed unless you are sure.'|i18n( 'design/eznewsletter/confirmremove_newslettertype' )}</p>

</div>

{* DESIGN: Content END *}</div></div></div>

<div class="controlbar">
{* DESIGN: Control bar START *}<div class="box-bc"><div class="box-ml"><div class="box-mr"><div class="box-tc"><div class="box-bl"><div class="box-br">
<div class="block">
<form action={$module.functions.list_type.uri|ezurl} method="post" name="NewsletterTypeListRemove">
    <input class="button" type="submit" name="ConfirmRemoveAllNewsletterTypeListButton" value="{'OK'|i18n( 'design/eznewsletter/confirmremove_newslettertype' )}" />
    <input type="hidden" name="RedirectAfterDelete" value="{concat('/newsletter/view_type/', $NewsletterTypeID )}" />
    <input type="hidden" name="NewsletterTypeID" value="{$NewsletterTypeID}" />
    <input class="button" type="submit" name="CancelButton" value="{'Cancel'|i18n( 'design/eznewsletter/confirmremove_newslettertype' )}" />
</form>

</div>

{* DESIGN: Control bar END *}</div></div></div></div></div></div>

</div>

</div>
