{* DO NOT EDIT THIS FILE! Use an override template instead. *}
{* eZNewsletter - edit onhold *}

<div class="context-block">
{* DESIGN: Header START *}<div class="box-header"><div class="box-tc"><div class="box-ml"><div class="box-mr"><div class="box-tl"><div class="box-tr">
<h1 class="context-title">{'Message on hold'|i18n( 'design/eznewsletter/edit_newsletter_onhold' )}</h1>

{* DESIGN: Mainline *}<div class="header-mainline"></div>

{* DESIGN: Header END *}</div></div></div></div></div></div>

{* DESIGN: Content START *}<div class="box-ml"><div class="box-mr"><div class="box-content">

{* Bounced sendnewsletteritem entry. *}
<div class="context-attributes">
<h3>{'Send item data:'|i18n( 'design/eznewsletter/edit_newsletter_onhold' )}</h3>
<div class="block">
<label>{'ID'|i18n('design/eznewsletter/edit_newsletter_onhold')}</label>
{$onhold_item.id|wash}

<label>{'Newsletter ID'|i18n('design/eznewsletter/edit_newsletter_onhold')}</label>
{$onhold_item.newsletter_id|wash}

<label>{'Newsletter name'|i18n('design/eznewsletter/edit_newsletter_onhold')}</label>
{$onhold_item.newsletter.name|wash}
</div>

<label>{'Sent to address'|i18n('design/eznewsletter/edit_newsletter_onhold')}</label>
{$onhold_item.user_data.email|wash}

<label>{'Recipient name'|i18n('design/eznewsletter/edit_newsletter_onhold')}</label>
{$onhold_item.user_data.name|wash}


</div>

<div class="block">
<form name="onhold_entry" method="post" action={concat( 'newsletter/list_bounce/onhold/', $onhold_item.id, '/' )|ezurl}>
<label>{'Set new sendout status'|i18n( 'design/eznewsletter/edit_newsletter_onhold' )}</label>
<select name="NewSendStatus">
{foreach $send_status as $key => $status}
    <option {cond( $onhold_item.send_status|eq( $key ), 'selected="selected"', '' )} value="{$key}">{$status|wash}</option>
{/foreach}
</select>

<input class="button" type="submit" name="EditOnHold" value="{'Set'|i18n( 'design/eznewsletter/edit_newsletter_onhold' )}" />
</form>
</div>

{* DESIGN: Content END *}</div></div></div>

{* Buttons. *}
<div class="controlbar">
{* DESIGN: Control bar START *}<div class="box-bc"><div class="box-ml"><div class="box-mr"><div class="box-tc"><div class="box-bl"><div class="box-br">
<div align="right"><a href={'newsletter/list_bounce/onhold/'|ezurl}>{'Back to on hold list'|i18n( 'design/eznewsletter/edit_newsletter_onhold' )} &gt;&gt;</a></div>
{* DESIGN: Control bar END *}</div></div></div></div></div></div>
</div>
</div>

