{* DO NOT EDIT THIS FILE! Use an override template instead. *}
{* eZNewsletter - subscriptions list *}

{if $warning|count}
    <div class="message-warning">
    <h2>{'The validation of your entries failed.'|i18n( 'design/eznewsletter/edit_newslettertype')}</h2>
    <ul>
    {foreach $warning as $warningmessage}
        <li>{$warningmessage|wash}</li>
    {/foreach}
    </ul>
    </div>
{/if}

<form name="edit_subscription" method="post" action={concat( '/newsletter/edit_subscription/', $subscription.id )|ezurl}>

<div class="context-block">
{* DESIGN: Header START *}<div class="box-header"><div class="box-tc"><div class="box-ml"><div class="box-mr"><div class="box-tl"><div class="box-tr">
<h2 class="context-title">{'Edit <%subscription_name> [Subscription]'|i18n( 'eznewsletter',, hash( '%subscription_name', $subscription.name ) )|wash}</h2>

{* DESIGN: Mainline *}<div class="header-mainline"></div>

{* DESIGN: Header END *}</div></div></div></div></div></div>

{* DESIGN: Content START *}<div class="box-ml"><div class="box-mr"><div class="box-content">

<div class="context-attributes">

    {* Vorname. *}
    <div class="block">
        <label>{"First name"|i18n( 'design/eznewsletter/edit_subscription' )}:</label>
        <input class="halfbox" id="subscriptionFirstname" type="text" name="Firstname" value="{$subscription.firstname|wash}" title="{'First name of the subscriber.'|i18n( 'design/eznewsletter/edit_subscription' )}"
               {cond( $subscription.user_id|gt(0), 'readonly="readonly"', '' )} />
    </div>

    {* Name. *}
    <div class="block">
        <label>{"Last name"|i18n( 'design/eznewsletter/edit_subscription' )}:</label>
        <input class="halfbox" id="subscriptionName" type="text" name="Name" value="{$subscription.name|wash}" title="{'Last name of the subscriber.'|i18n( 'design/eznewsletter/edit_subscription' )}"
               {cond( $subscription.user_id|gt(0), 'readonly="readonly"', '' )} />
    </div>

    {* Email. *}
    <div class="block">
        <label>{"Email"|i18n( 'design/eznewsletter/edit_subscription' )}:</label>
        <input class="halfbox" id="subscriptionEmail" type="text" name="Email" value="{$subscription.email|wash}" title="{'Email of the subscriber.'|i18n( 'design/eznewsletter/edit_subscription' )}"
               {cond( $subscription.user_id|gt(0), 'readonly="readonly"', '' )} />
    </div>


    {* Mobile Nr. *}
    <div class="block">
         <label>{"Mobile number"|i18n( 'design/eznewsletter/edit_subscription' )}:</label>
         <input class="halfbox" id="subscriptionMobile" type="text" name="Mobile" value="{$subscription.mobile|wash}" title="{'Mobile number of the subscriber.'|i18n( 'design/eznewsletter/edit_subscription' )}" />
    </div>

    {if $subscription.subscription_list.require_password}
        {* Password. *}
        <div class="block">
            <label>{"Password"|i18n( 'design/eznewsletter/edit_subscription' )}:</label>
            <input name="Password1" size="25" type="password" value="password" {cond( $subscription.user_id|gt(0), 'readonly="readonly"', '' )} />
            <input name="Password2" size="25" type="password" value="password" {cond( $subscription.user_id|gt(0), 'readonly="readonly"', '' )} />
        </div>
    {/if}

    {* eZ Publish user *}
    <div class="block">
        <label>{"eZ Publish user"|i18n( 'design/eznewsletter/edit_subscription' )}</label>
        {if $subscription.user}
            <a href={$subscription.user.contentobject.main_node.url_alias|ezurl}>{$subscription.user.contentobject.name|wash}</a>
        {/if}
        <input class="button" type="submit" name="BrowseUserButton" value="{'Select'|i18n( 'design/eznewsletter/edit_subscription' )}" title="{'Apply the changes and return to subscription list view.'|i18n( 'design/eznewsletter/edit_subscription' )}" />
        <input class="button" type="submit" name="UnsetUserButton" value="{'Remove'|i18n( 'design/eznewsletter/edit_subscription' )}" title="{'Apply the changes and return to subscription list view.'|i18n( 'design/eznewsletter/edit_subscription' )}" />
    </div>

    {* Status. *}
    <div class="block">
        <label>{"Status"|i18n( 'design/eznewsletter/edit_subscription' )}:</label>
        <select name="Status" title="{'Status'|i18n( 'design/eznewsletter/edit_subscription' )}">
        {foreach $status_map as $value => $name}
            <option value="{$value|wash}" {cond( $subscription.status|eq($value), 'selected="selected"', '')}>{$name|wash}</option>
        {/foreach}
        </select>
    </div>

    {*
     * <div class="block">
     *    <label>{"Vip"|i18n( 'design/eznewsletter/edit_subscription' )}:</label>
     *    <select name="Vip" title="{'VIP status'|i18n( 'design/eznewsletter/edit_subscription' )}">
     *    {foreach $vip_map as $value => $name}
     *        <option value="{$value|wash}" {cond( $subscription.vip|eq($value), 'selected="selected"', '')}>{$name|wash}</option>
     *   {/foreach}
     *    </select>
     * </div>
     *}


{* DESIGN: Content END *}</div></div></div>


    {* Buttons. *}
    <div class="controlbar">
{* DESIGN: Control bar START *}<div class="box-bc"><div class="box-ml"><div class="box-mr"><div class="box-tc"><div class="box-bl"><div class="box-br">
    <div class="block">
        <input class="button" type="submit" name="StoreButton" value="{'Ok'|i18n( 'design/eznewsletter/edit_subscription' )}" title="{'Apply the changes and return subscription list view.'|i18n( 'design/eznewsletter/edit_subscription' )}" />
        <input class="button" type="submit" name="CancelButton" value="{'Cancel'|i18n( 'design/eznewsletter/edit_subscription' )}" title="{'Cancel the changes and return to the subscriptions list.'|i18n( 'design/eznewsletter/edit_subscription' )}" />
        {*<a align="right" href={concat( 'newsletter/subscription_list/', $subscription.subscription_list.url_alias )|ezurl}>{'Back to subscription list'|i18n( 'eznewslettert' )} &gt;&gt;</a>*}
    </div>
{* DESIGN: Control bar END *}</div></div></div></div></div></div>
    </div>
</form>
