{* DO NOT EDIT THIS FILE! Use an override template instead. *}
{* eZNewsletter - subscriptions list *}

<form name="edit_subscription_list" method="post" action={concat( '/newsletter/edit_subscription_list/', $subscriptionList.url_alias )|ezurl}>

{if $warning|count}
    <div class="message-warning">
    <h2>{'The validation of your entries failed.'|i18n( 'design/eznewsletter/edit_subscription_list' )}</h2>
    <ul>
    {foreach $warning as $warningmessage}
	<li>{$warningmessage|wash}</li>
    {/foreach}
    </ul>
    </div>
{/if}

<div class="context-block">
{* DESIGN: Header START *}<div class="box-header"><div class="box-tc"><div class="box-ml"><div class="box-mr"><div class="box-tl"><div class="box-tr">
<h1 class="context-title">{'Edit <%subscription_list_name> [Subscription list]'|i18n( 'eznewsletter',, hash( '%subscription_list_name', $subscriptionList.name ) )|wash}</h1>

{* DESIGN: Mainline *}<div class="header-mainline"></div>

{* DESIGN: Header END *}</div></div></div></div></div></div>

{* DESIGN: Content START *}<div class="box-ml"><div class="box-mr"><div class="box-content">

<div class="context-attributes">

    {* Name. *}
    <div class="block">
        <label>{"Name"|i18n( 'design/eznewsletter/edit_subscription_list' )}:</label>
        <input class="halfbox" id="subscriptionListName" type="text" name="Name" value="{$subscriptionList.name|wash}" title="{'Name of the subscription list.'|i18n( 'design/eznewsletter/edit_subscription_list' )}" />
    </div>

    {* URL. *}
    <div class="block">
        <label>{"Registration URL"|i18n( 'design/eznewsletter/edit_subscription_list' )}:</label>
        <fieldset>
        <legend><label><input type="radio" name="RegistrationURL" {cond( $subscriptionList.url_type|eq(0), 'checked="checked"', '' )} value="0" />{'ID'|i18n( 'design/eznewsletter/edit_subscription_list' )}:</label></legend>
        {'URL : %url'|i18n( 'eznewsletter',,hash( '%url', concat( '/newsletter/register_subscription/', $subscriptionList.id )|ezurl ) )}
        </fieldset>
        <fieldset>
        <legend><label><input type="radio" name="RegistrationURL" {cond( $subscriptionList.url_type|eq(1), 'checked="checked"', '' )} value="1" />{'Name'|i18n( 'design/eznewsletter/edit_subscription_list' )}:</label></legend>
        {'URL'|i18n( 'design/eznewsletter/edit_subscription_list' )}:
        /newsletter/register_subscription/<input class="halfbox" id="subscriptionListURL" type="text" name="URLName" value="{$subscriptionList.url|wash}" title="{'URL to subscription.'|i18n( 'design/eznewsletter/edit_subscription_list' )}" />
        <input class="enabledbutton" type="submit" name="GenerateURLHash" value="{'Generate hash'|i18n( 'design/eznewsletter/edit_subscription_list' )}" title="{'Generate hash for URL.'|i18n( 'design/eznewsletter/edit_subscription_list' )}" />
        </fieldset>
    </div>

{*
<div class="block">
<label>{'Related objects'|i18n( 'design/eznewsletter/edit_subscription_list' )}:</label>
<div class="element">
    {if $subscriptionList.related_object_id_1}
        <ul><li>{$subscriptionList.related_object_1.name}</li></ul>
        <input class="button" type="submit" name="BrowseRelatedObject_1" value="{'Add related object'|i18n( 'design/eznewsletter/edit_subscription_list' )}" />
        <input class="button" type="submit" name="DeleteRelatedObject_1" value="{'Remove object location'|i18n( 'design/eznewsletter/edit_subscription_list' )}" />
        {else}
            {'No object relation selected'|i18n( 'design/eznewsletter/edit_subscription_list' )}&nbsp;
            <input class="button" type="submit" name="BrowseRelatedObject_1" value="{'Add related object'|i18n( 'design/eznewsletter/edit_subscription_list' )}" />
    {/if}
</div>
<div class="element">
    {if $subscriptionList.related_object_id_2}
        <ul><li>{$subscriptionList.related_object_2.name}</li></ul>
        <input class="button" type="submit" name="BrowseRelatedObject_2" value="{'Add related object'|i18n( 'design/eznewsletter/edit_subscription_list' )}" />
        <input class="button" type="submit" name="DeleteRelatedObject_2" value="{'Remove object location'|i18n( 'design/eznewsletter/edit_subscription_list' )}" />
        {else}
            {'No object relation selected'|i18n( 'design/eznewsletter/edit_subscription_list' )}&nbsp;
            <input class="button" type="submit" name="BrowseRelatedObject_2" value="{'Add related object'|i18n( 'design/eznewsletter/edit_subscription_list' )}" />
    {/if}
</div>
<div class="element">
    {if $subscriptionList.related_object_id_3}
        <ul><li>{$subscriptionList.related_object_3.name}</li></ul>
        <input class="button" type="submit" name="BrowseRelatedObject_3" value="{'Add related object'|i18n( 'design/eznewsletter/edit_subscription_list' )}" />
        <input class="button" type="submit" name="DeleteRelatedObject_3" value="{'Remove object location'|i18n( 'design/eznewsletter/edit_subscription_list' )}" />
        {else}
            {'No object relation selected'|i18n( 'design/eznewsletter/edit_subscription_list' )}&nbsp;
            <input class="button" type="submit" name="BrowseRelatedObject_3" value="{'Add related object'|i18n( 'design/eznewsletter/edit_subscription_list' )}" />
    {/if}
</div>
</div>
*}
    {* Description *}
    <div class="block">
        <label>{"Description"|i18n( 'design/eznewsletter/edit_subscription_list' )}:</label>
        <textarea class="halfbox" name="Description" rows="3" title="{'Use the description to explain the purpose of this subscription list.'|i18n( 'design/eznewsletter/edit_subscription_list' )}">{$subscriptionList.description|wash}</textarea>
    </div>

    {* Login steps. *}
    <div class="block">
        <label>{"Login steps"|i18n( 'design/eznewsletter/edit_subscription_list' )}:</label>
        <select name="LoginSteps" title="{'Login steps'|i18n( 'design/eznewsletter/edit_subscription_list' )}">
        {foreach $loginSteps_map as $value => $name}
            <option value="{$value|wash}" {cond( $subscriptionList.login_steps|eq($value), 'selected="selected"', '')}>{$name|wash}</option>
        {/foreach}
        </select>
    </div>

    {* Require password *}
    <div class="block">
        <label>{"Require password"|i18n( 'design/eznewsletter/edit_subscription_list' )}:</label>
        <input type="checkbox" name="RequirePassword" title="{'Require password'|i18n( 'design/eznewsletter/edit_subscription_list' )}" {cond( $subscriptionList.require_password, 'checked="checked"', '' )} >{'Require password'|i18n( 'design/eznewsletter/edit_subscription_list' )}</input>
    </div>

    {* Allow anonymous *}
    <div class="block">
        <label>{"Allow anonymous users"|i18n( 'design/eznewsletter/edit_subscription_list' )}:</label>
        <input type="checkbox" name="AllowAnonymous" title="{'Allow anonymous users'|i18n( 'design/eznewsletter/edit_subscription_list' )}" {cond( $subscriptionList.allow_anonymous, 'checked="checked"', '' )} >{'Allow anonymous users'|i18n( 'design/eznewsletter/edit_subscription_list' )}</input>
    </div>

    {* Auto confirm *}
    <div class="block">
        <label>{"Auto confirm registered users"|i18n( 'design/eznewsletter/edit_subscription_list' )}:</label>
        <input type="checkbox" name="AutoConfirmRegistered" title="{'Automatically confirm registered users'|i18n( 'design/eznewsletter/edit_subscription_list' )}" {cond( $subscriptionList.auto_confirm_registered, 'checked="checked"', '' )} >{'Auto confirm registered users'|i18n( 'design/eznewsletter/edit_subscription_list' )}</input>
    </div>

    {* Auto approve *}
    <div class="block">
        <label>{"Automatically approve registered users"|i18n( 'design/eznewsletter/edit_subscription_list' )}:</label>
        <input type="checkbox" name="AutoApproveRegistered" title="{'Automatically approve registered users'|i18n( 'design/eznewsletter/edit_subscription_list' )}" {cond( $subscriptionList.auto_approve_registered, 'checked="checked"', '' )} >{'Automatically approve registered users'|i18n( 'design/eznewsletter/edit_subscription_list' )}</input>
    </div>

    <div class="block">
	<label>{'Allowed siteaccesses'|i18n( 'design/eznewsletter/edit_newslettertype' )}:</label>
	{def $siteaccesses_list = ezini( 'SiteAccessSettings', 'AvailableSiteAccessList' )}
	<select name="AllowedSiteaccesses[]" multiple="multiple" size="10">
	{foreach $siteaccesses_list as $siteaccess_name}
	    <option value="{$siteaccess_name}" {cond( or( $subscriptionList.allowed_siteaccesses_array|contains($siteaccess_name), eq( $siteaccess_name, current_siteaccess() ) ), 'selected="selected"', '' )}>{$siteaccess_name|wash}</option>
	{/foreach}
	</select>
    </div>

{* DESIGN: Content END *}</div></div></div>


    {* Buttons. *}
    <div class="controlbar">
{* DESIGN: Control bar START *}<div class="box-bc"><div class="box-ml"><div class="box-mr"><div class="box-tc"><div class="box-bl"><div class="box-br">
    <div class="block">
    <input class="button" type="submit" name="StoreButton" value="{'Ok'|i18n( 'design/eznewsletter/edit_subscription_list' )}" title="{'Apply the changes and return to the subscription list view.'|i18n( 'design/eznewsletter/edit_subscription_list' )}" />
    <input class="button" type="submit" name="CancelButton" value="{'Cancel'|i18n( 'design/eznewsletter/edit_subscription_list' )}" title="{'Cancel the changes and return to the subscriptions list.'|i18n( 'design/eznewsletter/edit_subscription_list' )}" />
    </div>
{* DESIGN: Control bar END *}</div></div></div></div></div></div>
    </div>


</form>

