{* DO NOT EDIT THIS FILE! Use an override template instead. *}
{* eZNewsletter - list bounces *}
{def $bounceCount=fetch( newsletter, bounce_count )
     $bounceTypes=hash( 0, 'Soft bounce'|i18n( 'design/eznewsletter/list_newsletter_bounce' ),
                        1, 'Hard bounce'|i18n( 'design/eznewsletter/list_newsletter_bounce' ) )}

<form name="newsletterBounce" method="post" action={'/newsletter/list_bounce/all'|ezurl}>

<div class="context-block">
{* DESIGN: Header START *}<div class="box-header"><div class="box-tc"><div class="box-ml"><div class="box-mr"><div class="box-tl"><div class="box-tr">
<h1 class="context-title">{'Newsletter bounces'|i18n( 'design/eznewsletter/list_newsletter_bounce' )}</h1>

{* DESIGN: Mainline *}<div class="header-mainline"></div>

{* DESIGN: Header END *}</div></div></div></div></div></div>

{* DESIGN: Content START *}<div class="box-ml"><div class="box-mr"><div class="box-content overflow">

{* Items per page selector. *}
<div class="context-toolbar">
<div class="block">
<div class="left">
<p>
{switch match=$limit}
{case match=25}
<a href={concat( $module.functions.list_bounce.uri )|ezurl}>10</a>
<span class="current">25</span>
<a href={concat( $module.functions.list_bounce.uri, '/(limitkey)/3' )|ezurl}>50</a>
{/case}

{case match=50}
<a href={concat( $module.functions.list_bounce.uri )|ezurl}>10</a>
<a href={concat( $module.functions.list_bounce.uri, '/(limitkey)/2' )|ezurl}>25</a>
<span class="current">50</span>
{/case}

{case}
<span class="current">10</span>
<a href={concat( $module.functions.list_bounce.uri, '/(limitkey)/2' )|ezurl}>25</a>
<a href={concat( $module.functions.list_bounce.uri, '/(limitkey)/3' )|ezurl}>50</a>
{/case}

{/switch}
</p>
</div>
<div class="break"></div>
</div>
</div>

{* Newsletter bounce entry table. *}
<table class="list" cellspacing="0">
<tr>
    <th class="tight"><img src={'toggle-button-16x16.gif'|ezimage} alt="{'Invert selection'|i18n( 'design/eznewsletter/list_newsletter_bounce' )}" title="{'Invert selection.'|i18n( 'design/eznewsletter/list_newsletter_bounce' )}" onclick="ezjs_toggleCheckboxes( document.newsletterBounce, 'BounceIDArray[]' ); return false;" /></th>
    <th class="tight">{'ID'|i18n( 'design/eznewsletter/list_newsletter_bounce' )}</th>
    <th>{'Newsletter'|i18n( 'design/eznewsletter/list_newsletter_bounce' )}</th>
    <th>{'Sent to address'|i18n( 'design/eznewsletter/list_newsletter_bounce' )}</th>
    <th class="tight">{'Bounce count'|i18n( 'design/eznewsletter/list_newsletter_bounce' )}</th>
    <th>{'Bounce type'|i18n( 'design/eznewsletter/list_newsletter_bounce' )}</th>
    <th>{'Bounce arrived'|i18n( 'design/eznewsletter/list_newsletter_bounce' )}</th>
    <th>&nbsp;</th>
</tr>

{if $bounceCount|lt(1)}
<tr><td>&nbsp;</td><td>{'No bounces detected'|i18n( 'design/eznewsletter/list_newsletter_bounce' )}</td><td>&nbsp;</td><td>&nbsp;</td></tr>
{else}
{foreach $bounce_data_array as $bounceEntry
         sequence array( bglight, bgdark ) as $seq}
<tr class="{$seq}">
    <td class="number" align="right"><input type="checkbox" name="BounceIDArray[]" value="{$bounceEntry.id}" title="{'Select bounce to clear bounce entry.'|i18n( 'design/eznewsletter/list_newsletter_bounce' )}" /></td>
    <td>{$bounceEntry.id|wash}</td>
    <td>{$bounceEntry.newsletter_name|wash}</td>
    <td>{$bounceEntry.address|wash}</td>
    <td class="number">{$bounceEntry.bounce_count|wash}</td>
    <td>{$bounceTypes[$bounceEntry.bounce_type]|wash}</td>
    <td>{$bounceEntry.bounce_arrived|l10n( shortdatetime )}</td>
         {if $bounceEntry.newslettersenditem_id|eq(0)|not}
	    <td><a href={concat( 'newsletter/list_bounce/all/', $bounceEntry.newslettersenditem_id, '/' )|ezurl}><img src={'edit.gif'|ezimage}</a></td>
         {else} 
    	    <td>&nbsp;</td>
	{/if}
    </tr>
{/foreach}
{/if}

</table>

{* Navigator. *}
<div class="context-toolbar">
{include name=navigator
         uri='design:navigator/google.tpl'
         page_uri='/newsletter/list_bounce'
         item_count=$bounceCount
         view_parameters=$view_parameters
         item_limit=$limit}
</div>

{* DESIGN: Content END *}</div></div></div>

{* Buttons. *}
<div class="controlbar">
{* DESIGN: Control bar START *}<div class="box-bc"><div class="box-ml"><div class="box-mr"><div class="box-tc"><div class="box-bl"><div class="box-br">
<div class="block">
<input class="button" type="submit" name="RemoveBounceEntryButton" value="{'Remove selected'|i18n( 'design/eznewsletter/list_newsletter_bounce' )}" title="{'Remove selected bounce entries.'|i18n( 'design/eznewsletter/list_newsletter_bounce' )}" />
<input class="button" type="submit" name="RemoveAllBounceEntryButton" value="{'Remove all'|i18n( 'design/eznewsletter/list_newsletter_bounce' )}" title="{'Remove all bounce entries.'|i18n( 'design/eznewsletter/list_newsletter_bounce' )}" />
</div>  
{* DESIGN: Control bar END *}</div></div></div></div></div></div>
</div>
</div>
</form>

