{* DO NOT EDIT THIS FILE! Use an override template instead. *}
{* eZNewsletter - list *}
{def $newsletterTypeCount=fetch( newsletter, newsletter_type_count, hash( 'use_filter', true() ) )
     $newsletterCount=fetch( newsletter, newsletter_count )}

<form name="newsletterTypes" method="post" action={'/newsletter/list_type/'|ezurl}>

<div class="context-block">
{* DESIGN: Header START *}<div class="box-header"><div class="box-tc"><div class="box-ml"><div class="box-mr"><div class="box-tl"><div class="box-tr">
<h1 class="context-title">{'Newsletter types'|i18n( 'design/eznewsletter/list_newsletter_type' )}</h1>

{* DESIGN: Mainline *}<div class="header-mainline"></div>

{* DESIGN: Header END *}</div></div></div></div></div></div>

{* DESIGN: Content START *}<div class="box-ml"><div class="box-mr"><div class="box-content overflow">

{* Items per page selector. *}
<div class="context-toolbar">
<div class="block">
<div class="left">
<p>
{switch match=$limit}
{case match=25}
<a href={concat( $module.functions.list_type.uri )|ezurl}>10</a>
<span class="current">25</span>
<a href={concat( $module.functions.list_type.uri, '/(limitkey)/3' )|ezurl}>50</a>
{/case}

{case match=50}
<a href={concat( $module.functions.list_type.uri )|ezurl}>10</a>
<a href={concat( $module.functions.list_type.uri, '/(limitkey)/2' )|ezurl}>25</a>
<span class="current">50</span>
{/case}

{case}
<span class="current">10</span>
<a href={concat( $module.functions.list_type.uri, '/(limitkey)/2' )|ezurl}>25</a>
<a href={concat( $module.functions.list_type.uri, '/(limitkey)/3' )|ezurl}>50</a>
{/case}

{/switch}
</p>
</div>
<div class="break"></div>
</div>
</div>

{* Newsletter type table. *}
<table class="list" cellspacing="0">
<tr>
    <th class="tight"><img src={'toggle-button-16x16.gif'|ezimage} alt="{'Invert selection'|i18n( 'design/eznewsletter/list_newsletter_type' )}" title="{'Invert selection.'|i18n( 'design/eznewsletter/list_newsletter_type' )}" onclick="ezjs_toggleCheckboxes( document.newsletterTypes, 'NewsletterTypeIDArray[]' ); return false;" /></th>
    <th>{'Name'|i18n( 'design/eznewsletter/list_newsletter_type' )}</th>
    <th>{'Created by'|i18n( 'design/eznewsletter/list_newsletter_type' )}</th>
    <th>{'Newsletter placement'|i18n( 'design/eznewsletter/list_newsletter_type' )}</th>
    <th>{'Created on'|i18n( 'design/eznewsletter/list_newsletter_type' )}</th>
    <th class="tight">{'ID'|i18n( 'design/eznewsletter/list_newsletter_type' )}</th>
{*    <th class="tight">{'New'|i18n( 'design/eznewsletter/list_newsletter_type' )}</th> *}
    <th class="tight">&nbsp;</th>
</tr>
{if $newsletterTypeCount|lt(1)}
<tr><td>&nbsp;</td><td>{'No newsletters defined'|i18n( 'design/eznewsletter/list_newsletter_type' )}</td><td>&nbsp;</td><td>&nbsp;</td></tr>
{else}
{foreach $newsletter_type_array as $newsletterItem
         sequence array( bglight, bgdark ) as $seq}
<tr class="{$seq}">
    <td><input type="checkbox" name="NewsletterTypeIDArray[]" value="{$newsletterItem.id}" title="{'Select newsletter type for removal.'|i18n( 'design/eznewsletter/list_newsletter_type' )}" /></td>
    <td>{'newsletter'|icon( 'small', 'Newsletter'|i18n( 'design/eznewsletter/list_newsletter_type' ) )}&nbsp;<a href={concat( '/newsletter/view_type/', $newsletterItem.id, '/' )|ezurl}>{$newsletterItem.name|wash}</a></td>
    <td><a href={$newsletterItem.creator.contentobject.main_node.url_alias|ezurl}>{$newsletterItem.creator.contentobject.name|wash}</a></td>
    <td><a href={$newsletterItem.article_pool_object.main_node.url_alias|ezurl}>{$newsletterItem.article_pool_object.name|wash}</a></td>
    <td>{$newsletterItem.created|l10n( shortdatetime )}</td>
    <td class="number" align="right">{$newsletterItem.id}</td>
    <td><a href={concat( '/newsletter/edit_type/', $newsletterItem.id, '/' )|ezurl}><img src={'edit.gif'|ezimage} alt="{'Edit'|i18n( 'design/eznewsletter/list_newsletter_type' )}" title="{'Edit the <%newsletter_name> newsletter type.'|i18n( 'design/eznewsletter/list_newsletter_type',, hash( '%newsletter_name', $newsletterItem.name ) )|wash}" /></a></td>
    </tr>
{/foreach}
{/if}
</table>

{* Navigator. *}
<div class="context-toolbar">
{include name=navigator
         uri='design:navigator/google.tpl'
         page_uri='/newsletter/list_type'
         item_count=$newsletterTypeCount
         view_parameters=$view_parameters
         item_limit=$limit}
</div>

{* DESIGN: Content END *}</div></div></div>

{* Buttons. *}
<div class="controlbar">
{* DESIGN: Control bar START *}<div class="box-bc"><div class="box-ml"><div class="box-mr"><div class="box-tc"><div class="box-bl"><div class="box-br">
<div class="block">
<input class="button" type="submit" name="RemoveNewslettertypeButton" value="{'Remove selected'|i18n( 'design/eznewsletter/list_newsletter_type' )}" title="{'Remove selected newsletter types.'|i18n( 'design/eznewsletter/list_newsletter_type' )}" />
<input class="button" type="submit" name="CreateNewslettertypeButton" value="{'New newsletter type'|i18n( 'design/eznewsletter/list_newsletter_type' )}" title="{'Create a new newsletter type.'|i18n( 'design/eznewsletter/list_newsletter_type' )}" />
</div>
{* DESIGN: Control bar END *}</div></div></div></div></div></div>
</div>
</div>
</form>

