{* DO NOT EDIT THIS FILE! Use an override template instead. *}
{* eZNewsletter - list onhold *}
{def $onHoldCount=fetch( newsletter, onhold_count, hash( 'status', 2 ) )
     $bounceTypes=hash( 0, 'Soft bounce'|i18n( 'design/eznewsletter/list_newsletter_onhold' ),
                        1, 'Hard bounce'|i18n( 'design/eznewsletter/list_newsletter_onhold' ) )}

<form name="newsletterOnHold" method="post" action={'/newsletter/list_bounce/onhold'|ezurl}>

<div class="context-block">
{* DESIGN: Header START *}<div class="box-header"><div class="box-tc"><div class="box-ml"><div class="box-mr"><div class="box-tl"><div class="box-tr">
<h1 class="context-title">{'Send items on hold'|i18n( 'design/eznewsletter/list_newsletter_onhold' )}</h1>

{* DESIGN: Mainline *}<div class="header-mainline"></div>

{* DESIGN: Header END *}</div></div></div></div></div></div>

{* DESIGN: Content START *}<div class="box-ml"><div class="box-mr"><div class="box-content overflow">

{* Items per page selector. *}
<div class="context-toolbar">
<div class="block">
<div class="left">
<p>
{switch match=$limit}
{case match=25}
<a href={concat( $module.functions.list_bounce.uri, '/onhold' )|ezurl}>10</a>
<span class="current">25</span>
<a href={concat( $module.functions.list_bounce.uri, '/onhold/(limitkey)/3' )|ezurl}>50</a>
{/case}

{case match=50}
<a href={concat( $module.functions.list_bounce.uri, '/onhold' )|ezurl}>10</a>
<a href={concat( $module.functions.list_bounce.uri, '/onhold/(limitkey)/2' )|ezurl}>25</a>
<span class="current">50</span>
{/case}

{case}
<span class="current">10</span>
<a href={concat( $module.functions.list_bounce.uri, '/onhold/(limitkey)/2' )|ezurl}>25</a>
<a href={concat( $module.functions.list_bounce.uri, '/onhold/(limitkey)/3' )|ezurl}>50</a>
{/case}

{/switch}
</p>
</div>
<div class="break"></div>
</div>
</div>

{* Send items on hold table. *}
<table class="list" cellspacing="0">
<tr>
    <th class="tight"><img src={'toggle-button-16x16.gif'|ezimage} alt="{'Invert selection'|i18n( 'design/eznewsletter/list_newsletter_onhold' )}" title="{'Invert selection.'|i18n( 'design/eznewsletter/list_newsletter_onhold' )}" onclick="ezjs_toggleCheckboxes( document.newsletterOnHold, 'OnHoldIDArray[]' ); return false;" /></th>
    <th class="tight">{'ID'|i18n( 'design/eznewsletter/list_newsletter_onhold' )}</th>
    <th>{'Newsletter'|i18n( 'design/eznewsletter/list_newsletter_onhold' )}</th>
    <th>{'Sent to address'|i18n( 'design/eznewsletter/list_newsletter_onhold' )}</th>
    <th>{'Recipient name'|i18n( 'design/eznewsletter/list_newsletter_onhold' )}</th>
    <th class="tight">&nbsp;</th>
</tr>

{if $onHoldCount|lt(1)}
	<tr><td>&nbsp;</td><td>{'No messages on hold detected'|i18n( 'design/eznewsletter/list_newsletter_onhold' )}</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td></tr>
{else}
{foreach $onhold_items as $onHoldEntry sequence array( bglight, bgdark ) as $seq}
	<tr class="{$seq}">
	    <td class="number" align="right"><input type="checkbox" name="OnHoldIDArray[]" value="{$onHoldEntry.id}" title="{'Select an iten on hold to delete the scheduled sendout.'|i18n( 'design/eznewsletter/list_newsletter_onhold' )}" /></td>
	    <td>{$onHoldEntry.id|wash}</td>
	    <td>{$onHoldEntry.newsletter.name|wash}</td>
	    <td>{$onHoldEntry.user_data.email|wash}</td>
	    <td>{$onHoldEntry.user_data.name|wash}</td>
	    <td><a href={concat( 'newsletter/list_bounce/onhold/', $onHoldEntry.id, '/' )|ezurl}><img src={'edit.gif'|ezimage} /></a></td>
	</tr>
{/foreach}
{/if}

</table>

{* Navigator. *}
<div class="context-toolbar">
{include name=navigator
         uri='design:navigator/google.tpl'
         page_uri='/newsletter/list_bounce/onhold'
         item_count=$onHoldCount
         view_parameters=$view_parameters
         item_limit=$limit}
</div>

{* DESIGN: Content END *}</div></div></div>

{* Buttons. *}
<div class="controlbar">
{* DESIGN: Control bar START *}<div class="box-bc"><div class="box-ml"><div class="box-mr"><div class="box-tc"><div class="box-bl"><div class="box-br">
<div class="block">
<input class="button" type="submit" name="RemoveOnHoldEntryButton" value="{'Remove selected'|i18n( 'design/eznewsletter/list_newsletter_onhold' )}" title="{'Remove selected entries on hold.'|i18n( 'design/eznewsletter/list_newsletter_onhold' )}" />
</div>
{* DESIGN: Control bar END *}</div></div></div></div></div></div>
</div>
</div>
</form>

