{* DO NOT EDIT THIS FILE! Use an override template instead. *}
{* eZNewsletter - list bounces *}
{def $bounceCount=fetch( newsletter, grouped_bounce_count )
	 $bounceTypes=hash( 0, 'Soft bounce'|i18n( 'design/eznewsletter/list_newsletter_bounce' ),
                        1, 'Hard bounce'|i18n( 'design/eznewsletter/list_newsletter_bounce' ) )}

<form name="newsletterBounce" method="post" action="">

<div class="context-block">
{* DESIGN: Header START *}<div class="box-header"><div class="box-tc"><div class="box-ml"><div class="box-mr"><div class="box-tl"><div class="box-tr">
<h1 class="context-title">{'Newsletter bounces'|i18n( 'design/eznewsletter/list_newsletter_bounce' )}</h1>

{* DESIGN: Mainline *}<div class="header-mainline"></div>

{* DESIGN: Header END *}</div></div></div></div></div></div>

{* DESIGN: Content START *}<div class="box-ml"><div class="box-mr"><div class="box-content overflow">

{* Items per page selector. *}
<div class="context-toolbar">
<div class="block">
<div class="left">
<p>
{switch match=$limit}
{case match=25}
<a href={concat( $module.functions.list_bounce.uri )|ezurl}>10</a>
<span class="current">25</span>
<a href={concat( $module.functions.list_bounce.uri, '/(limitkey)/3' )|ezurl}>50</a>
{/case}

{case match=50}
<a href={concat( $module.functions.list_bounce.uri )|ezurl}>10</a>
<a href={concat( $module.functions.list_bounce.uri, '/(limitkey)/2' )|ezurl}>25</a>
<span class="current">50</span>
{/case}

{case}
<span class="current">10</span>
<a href={concat( $module.functions.list_bounce.uri, '/(limitkey)/2' )|ezurl}>25</a>
<a href={concat( $module.functions.list_bounce.uri, '/(limitkey)/3' )|ezurl}>50</a>
{/case}

{/switch}
</p>
</div>
<div class="break"></div>
</div>
</div>

{* Newsletter bounce entry table. *}
<table class="list" cellspacing="0">
<tr>
    <th class="tight"><img src={'toggle-button-16x16.gif'|ezimage} alt="{'Invert selection'|i18n( 'design/eznewsletter/list_newsletter_bounce' )}" title="{'Invert selection.'|i18n( 'design/eznewsletter/list_newsletter_bounce' )}" onclick="ezjs_toggleCheckboxes( document.newsletterBounce, 'MailArray[]' ); return false;" /></th>
    <th>{'Mail'|i18n( 'design/eznewsletter/list_newsletter_bounce' )}</th>
    <th>{'Subscriptions'|i18n( 'design/eznewsletter/list_newsletter_bounce' )}</th>
    <th>{'Bounces'|i18n( 'design/eznewsletter/list_newsletter_bounce' )}</th>
</tr>

{if $bounceCount|eq(0)}
<tr><td>&nbsp;</td><td>{'No bounces detected'|i18n( 'design/eznewsletter/list_newsletter_bounce' )}</td><td>&nbsp;</td><td>&nbsp;</td></tr>
{else}
{foreach $bounce_data_array as $bounceEntry sequence array( bglight, bgdark ) as $seq}
	<tr class="{$seq}">
	    <td class="number" align="right">
	    	<input type="checkbox" name="MailArray[]" value="{$bounceEntry.mail|wash()}" title="{'Select the checkbox to use further actions on this entry by clicking the buttons below.'|i18n( 'design/eznewsletter/list_newsletter_bounce' )}" />
	    </td>
	    <td>
	    	{$bounceEntry.mail|wash()}
	    	<ul>
	    		<li><strong>{'Hardbounce Count'|i18n( 'design/eznewsletter/list_newsletter_bounce' )}:</strong> {$bounceEntry.hb_count}</li>
	    		<li><strong>{'Softbounce Count'|i18n( 'design/eznewsletter/list_newsletter_bounce' )}:</strong> {$bounceEntry.sb_count}</li>
	    	</ul>
	    </td>
		<td>
			{foreach $bounceEntry.subscriptions as $subscription_object}
				{if $subscription_object}
					<div class="block">
						<div class="element">
							<label>{'Subscription list'|i18n( 'design/eznewsletter/view_newsletter_bounce' )}</label>
							{$subscription_object.subscription_list.name|wash}
						</div>
						
						<div class="element">
							<label>{'Status'|i18n( 'design/eznewsletter/view_newsletter_bounce' )}</label>
							{$statusNames[$subscription_object.status]|wash}
						</div>
					</div>
				
					<div class="block">
						<form name="subscription_entry" method="post" action="">
							<label>{'Set new subscription status'|i18n( 'design/eznewsletter/view_newsletter_bounce' )}</label>
							<select name="NewSubscriptionStatus">
								{foreach $statusNames as $key => $status}
								    <option {cond( $subscription_object.status|eq( $key ), 'selected="selected"', '' )} value="{$key}">{$status|wash}</option>
								{/foreach}
							</select>
							<input type="hidden" value="{$subscription_object.id}" name="SubscriptionID" />
							<input class="button" type="submit" name="EditButton" value="{'Set'|i18n( 'design/eznewsletter/view_newsletter_bounce' )}" />
						</form>
					</div>
				{/if}
			{/foreach}
		</td>
		<td>
			{foreach $bounceEntry.bounces as $bounce_data}
				<div class="block">
					{$bounce_data.newsletter_name} ({$bounce_data.bounce_arrived|l10n( shortdatetime )})
					<a title="{'show more details'|i18n( 'design/eznewsletter/list_newsletter_bounce' )}" href={concat( 'newsletter/list_bounce/all/', $bounce_data.newslettersenditem_id, '/' )|ezurl()}>
			    		<img src={'edit.gif'|ezimage()} />
			    	</a>
				</div>
			{/foreach}
	    </td>
	</tr>
{/foreach}
{/if}

</table>

{* Navigator. *}
<div class="context-toolbar">
{include name=navigator
         uri='design:navigator/google.tpl'
         page_uri='/newsletter/list_bounce'
         item_count=$bounceCount
         view_parameters=$view_parameters
         item_limit=$limit}
</div>

{* DESIGN: Content END *}</div></div></div>

{* Buttons. *}
<div class="controlbar">
{* DESIGN: Control bar START *}<div class="box-bc"><div class="box-ml"><div class="box-mr"><div class="box-tc"><div class="box-bl"><div class="box-br">
<div class="block">
<input class="button" type="submit" name="RemoveBounceEntryButton" value="{'Remove selected bounces'|i18n( 'design/eznewsletter/list_newsletter_bounce' )}" title="{'Remove selected bounce entries.'|i18n( 'design/eznewsletter/list_newsletter_bounce' )}" />
<input class="button" type="submit" name="RemoveAndUnSubscribeButton" value="{'Remove bounces & unsubscribe'|i18n( 'design/eznewsletter/list_newsletter_bounce' )}" title="{'Remove all Bounces for the selected mails and unsubscribe user everywhere.'|i18n( 'design/eznewsletter/list_newsletter_bounce' )}" />
<input class="button" type="submit" name="RemoveAllBounceEntryButton" value="{'Remove all bounces'|i18n( 'design/eznewsletter/list_newsletter_bounce' )}" title="{'Remove all bounce entries.'|i18n( 'design/eznewsletter/list_newsletter_bounce' )}" />
</div>  
{* DESIGN: Control bar END *}</div></div></div></div></div></div>
</div>
</div>
</form>