{* DO NOT EDIT THIS FILE! Use an override template instead. *}
{* eZNewsletter - subscriptions list *}
{def $subscriptionListCount=fetch( newsletter, subscription_list_count, hash( 'use_filter', true() ) )
     $base_uri=concat( 'newsletter/list_subscriptions/(offset)/', $view_parameters.offset, '/(limit)/', $view_parameters.limit )}

<form name="subscription_list" method="post" action={$base_uri|ezurl}>

<div class="context-block">
{* DESIGN: Header START *}<div class="box-header"><div class="box-tc"><div class="box-ml"><div class="box-mr"><div class="box-tl"><div class="box-tr">
<h1 class="context-title">{'Subscription lists'|i18n( 'design/eznewsletter/list_subscriptions' )}</h1>

{* DESIGN: Mainline *}<div class="header-mainline"></div>

{* DESIGN: Header END *}</div></div></div></div></div></div>

{* DESIGN: Content START *}<div class="box-ml"><div class="box-mr"><div class="box-content">

{* Items per page selector. *}
<div class="context-toolbar">
<div class="block">
<div class="left">
<p>
{switch match=$limit}
{case match=25}
<a href={concat( $base_uri, '/(limit)/1' )|ezurl}>10</a>
<span class="current">25</span>
<a href={concat( $base_uri, '/(limit)/3' )|ezurl}>50</a>
{/case}

{case match=50}
<a href={concat( $base_uri, '/(limit)/1' )|ezurl}>10</a>
<a href={concat( $base_uri, '/(limit)/2' )|ezurl}>25</a>
<span class="current">50</span>
{/case}

{case}
<span class="current">10</span>
<a href={concat( $base_uri, '/(limit)/2' )|ezurl}>25</a>
<a href={concat( $base_uri, '/(limit)/3' )|ezurl}>50</a>
{/case}

{/switch}
</p>
</div>
<div class="break"></div>
</div>
</div>

{* Subscription list table. *}
<table class="list" cellspacing="0">
<tr>
    <th class="tight"><img src={'toggle-button-16x16.gif'|ezimage} alt="{'Invert selection'|i18n( 'design/eznewsletter/list_subscriptions' )}" title="{'Invert selection.'|i18n( 'design/eznewsletter/list_subscriptions' )}" onclick="ezjs_toggleCheckboxes( document.subscription_list, 'SubscriptionListIDArray[]' ); return false;" /></th>
    <th class="tight">{'ID'|i18n('design/eznewsletter/list_subscriptions')}</th>
    <th>{'Name'|i18n('design/eznewsletter/list_subscriptions')}</th>
    <th>{'Creator'|i18n('design/eznewsletter/list_subscriptions')}</th>
    <th>{'Created'|i18n('design/eznewsletter/list_subscriptions')}</th>
    <th>{'Subscribers'|i18n('design/eznewsletter/list_subscriptions')}</th>
    <th class="tight">&nbsp;</th>
</tr>
{foreach $subscriptionlist_array as $subscriptionList
         sequence array( bglight, bgdark ) as $seq}
<tr class="{$seq}">
    <td><input type="checkbox" name="SubscriptionListIDArray[]" value="{$subscriptionList.id}" title="{'Select subscription list for removal.'|i18n( 'design/eznewsletter/list_subscriptions' )}" /></td>
    <td class="number"><a href={concat( '/newsletter/subscription_list/', $subscriptionList.url_alias )|ezurl}>{$subscriptionList.id}</a></td>
    <td><a href={concat( '/newsletter/subscription_list/', $subscriptionList.url_alias )|ezurl}>{$subscriptionList.name|wash}</a></td>
    <td><a href={$subscriptionList.creator.contentobject.main_node.url_alias|ezurl}>{$subscriptionList.creator.contentobject.name|wash}</a></td>
    <td>{$subscriptionList.created|l10n( shortdatetime )}</td>
    <td class="number">{$subscriptionList.subscription_count|wash}</td>
    <td><a href={concat( '/newsletter/edit_subscription_list/', $subscriptionList.url_alias )|ezurl}><img src={'edit.gif'|ezimage} alt="{'Edit'|i18n( 'design/eznewsletter/list_subscriptions' )}" title="{'Edit the <%newsletter_name> subscription list.'|i18n( 'eznewsletter',, hash( '%newsletter_name', $subscriptionList.name ) )|wash}" /></a></td>
    </tr>
{/foreach}
</table>
 
{* Navigator. *}
<div class="context-toolbar">
{include name=navigator
         uri='design:navigator/google.tpl'
         page_uri='newsletter/list_subscriptions'
         item_count=$subscriptionListCount
         view_parameters=$view_parameters
         item_limit=$limit}
</div>

{* DESIGN: Content END *}</div></div></div>

{* Buttons. *}
<div class="controlbar">
{* DESIGN: Control bar START *}<div class="box-bc"><div class="box-ml"><div class="box-mr"><div class="box-tc"><div class="box-bl"><div class="box-br">
<div class="block">
<input class="button" type="submit" name="RemoveSubscriptionListButton" value="{'Remove selected'|i18n( 'design/eznewsletter/list_subscriptions' )}" title="{'Remove selected subscription list.'|i18n( 'design/eznewsletter/list_subscriptions' )}" />
<input class="button" type="submit" name="CreateSubscriptionListButton" value="{'New subscription list'|i18n( 'design/eznewsletter/list_subscriptions' )}" title="{'Create a new subscription list.'|i18n( 'design/eznewsletter/list_subscriptions' )}" />
</div>
{* DESIGN: Control bar END *}</div></div></div></div></div></div>

</form>
