{* DO NOT EDIT THIS FILE! Use an override template instead. *}
{* eZNewsletter - view newsletter type *}

{* fetch and set vars for googlebar *}
{let $item_type=ezpreference( 'admin_list_limit' )
    $number_of_items=min( $item_type, 3)|choose( 10,10, 25, 50 )
}

{def $base_uri=concat( '/newsletter/list_inprogress/', $newsletter_type.id)}

<form name="newsletter_list" method="post" action={$base_uri|ezurl}>

<div class="context-block">
{* DESIGN: Header START *}<div class="box-header"><div class="box-tc"><div class="box-ml"><div class="box-mr"><div class="box-tl"><div class="box-tr">
<h2 class="context-title">{'Recurring newsletter'|i18n( 'design/eznewsletter/list_recurring' )} [ {$newsletter_type.name} ]</h1>

{* DESIGN: Mainline *}<div class="header-mainline"></div>

{* DESIGN: Header END *}</div></div></div></div></div></div>

{* DESIGN: Content START *}<div class="box-ml"><div class="box-mr"><div class="box-content overflow">

{* Items per page selector. *}
<div class="context-toolbar">
<div class="block">
<div class="left">

<p>
{switch match=$number_of_items}
    {case match=25}
    <a href={concat('/user/preferences/set/admin_list_limit/1',$base_uri)|ezurl}>10</a>
    <span class="current">25</span>
    <a href={concat('/user/preferences/set/admin_list_limit/3',$base_uri)|ezurl}>50</a>
    {/case}
    {case match=50}
        <a href={concat('/user/preferences/set/admin_list_limit/1',$base_uri)|ezurl}>10</a>
        <a href={concat('/user/preferences/set/admin_list_limit/2',$base_uri)|ezurl}>25</a>
        <span class="current">50</span>
    {/case}

    {case}
        <span class="current">10</span>
        <a href={concat('/user/preferences/set/admin_list_limit/2',$base_uri)|ezurl}>25</a>
        <a href={concat('/user/preferences/set/admin_list_limit/3',$base_uri)|ezurl}>50</a>
    {/case}
{/switch}
</p>

</div>
<div class="break"></div>
</div>
</div>

{* Newsletter list table. *}
<table class="list" cellspacing="0">
<tr>
    <th class="tight">{'ID'|i18n('eznewslettert')}</th>
    <th>{'Name'|i18n( 'design/eznewsletter/list_recurring' )}</th>
    <th>{'Creator'|i18n( 'design/eznewsletter/list_recurring' )}</th>
    <th>{'Created'|i18n( 'design/eznewsletter/list_recurring' )}</th>
    <th>{'Send date'|i18n( 'design/eznewsletter/list_recurring' )}</th>
    <th>{'Send status'|i18n( 'design/eznewsletter/list_recurring' )}</th>
    <th>{'Condition'|i18n( 'design/eznewsletter/list_recurring' )}</th>
    <th>{'Type'|i18n( 'design/eznewsletter/list_recurring' )}</th>
    <th>{'Value'|i18n( 'design/eznewsletter/list_recurring' )}</th>
    <th>&nbsp;</th>
</tr>

{foreach fetch( newsletter, newsletter_list_by_type, hash( type_id, $newsletter_type.id, is_sent, false(), offset, $offset, limit, $number_of_items, $grouping, true(), recurring, true() ) ) as $newsletter
         sequence array( bglight, bgdark ) as $seq}
<tr class="{$seq}">
    <td class="number">{$newsletter.id}</td>
    <td><a href="{concat( 'newsletter/preview/', $newsletter.contentobject.id, '/', $newsletter.contentobject.current_version)|ezurl(no)}">
    {$newsletter.contentobject.name|wash}</a></td>
    <td><a href={$newsletter.creator.contentobject.main_node.url_alias|ezurl}>{$newsletter.creator.contentobject.name|wash}</a></td>
    <td>{$newsletter.created|l10n( shortdatetime )}</td>
    <td>{$newsletter.send_date|l10n( shortdatetime )}</td>
    <td>{$newsletter.send_status_name_map[$newsletter.send_status]|wash}</td>
    <td>{$newsletter.recurrence_condition|wash}</td>
    <td>{$newsletter.recurrence_name_map[$newsletter.recurrence_type]|wash}</td>
    <td>{$newsletter.recurrence_value}</td>
    <td><a href={$newsletter.contentobject.main_node.url_alias|ezurl}>
        <img src={'preview.gif'|ezimage} title="{'Preview newsletter'|i18n( 'design/eznewsletter/list_recurring' )}">
        </a>
    </td>
    </tr>
{/foreach}
</table>

{* Navigator. *}
<div class="context-toolbar">
{include name=navigator
         uri='design:navigator/google.tpl'
         page_uri=$base_uri
         item_count=fetch( newsletter, newsletter_list_by_type, hash( type_id, $newsletter_type.id, is_sent, false(), offset, -1, limit, -1, $grouping, true(), recurring, true() ) )|count()
         item_limit=$number_of_items
     view_parameters=$view_parameters}
</div>

{* DESIGN: Content END *}</div></div></div>

{* Buttons. *}
<div class="controlbar">
{* DESIGN: Control bar START *}<div class="box-bc"><div class="box-ml"><div class="box-mr"><div class="box-tc"><div class="box-bl"><div class="box-br">
{* DESIGN: Control bar END *}</div></div></div></div></div></div>
</div></div></div>

</form>
