{* DO NOT EDIT THIS FILE! Use an override template instead. *}
{* eZNewsletter - robinson list *}

{if is_set($warning)}
    <div class="message-warning">
        <h2>{$warning|wash}</h2>
    </div>
{/if}

<form name="robinson_edit" method="post" action={'/newsletter/robinson_user'|ezurl}>

<div class="context-block">
{* DESIGN: Header START *}<div class="box-header"><div class="box-tc"><div class="box-ml"><div class="box-mr"><div class="box-tl"><div class="box-tr">
<h2 class="context-title">{'Opt-out list settings'|i18n( 'design/eznewsletter/robinson_user' )}</h2>
{* DESIGN: Mainline *}<div class="header-mainline"></div>

{* DESIGN: Header END *}</div></div></div></div></div></div>

{* DESIGN: Content START *}<div class="box-ml"><div class="box-mr"><div class="box-content">

<div class="context-attributes">

    {* Value. *}
    <div class="block">
        <label>{"Email address"|i18n( 'design/eznewsletter/robinson_user' )}</label>
        <input class="halfbox" id="RobinsonlistEntry_Email" type="text" name="RobinsonlistEntry_Email" {if is_set($robinson_email)}{concat(' value="',$robinson_email,'" ')}{/if} title="{'Email address'|i18n( 'design/eznewsletter/robinson_user' )}" />
    </div>

    {* Value. *}
    <div class="block">
        <label>{"Mobile phone number"|i18n( 'design/eznewsletter/robinson_user' )}</label>
        <input class="halfbox" id="RobinsonlistEntry_Mobile" type="text" name="RobinsonlistEntry_Mobile" {if is_set($robinson_mobile)}{concat(' value="',$robinson_mobile,'" ')}{/if} title="{'Mobile phone number'|i18n( 'design/eznewsletter/robinson_user' )}" />
    </div>

{* DESIGN: Content END *}</div></div></div>


    {* Buttons. *}
    <div class="controlbar">
{* DESIGN: Control bar START *}<div class="box-bc"><div class="box-ml"><div class="box-mr"><div class="box-tc"><div class="box-bl"><div class="box-br">
    <div class="block">
        <input class="button" type="submit" name="AddButton" value="{'Add to list'|i18n( 'design/eznewsletter/robinson_user' )}" title="{'Apply the changes and return to the opt-out list.'|i18n( 'design/eznewsletter/robinson_user' )}" />
        <input class="button" type="submit" name="RemoveButton" value="{'Remove from list'|i18n( 'design/eznewsletter/robinson_user' )}" title="{'Apply the changes and return to the opt-out list.'|i18n( 'design/eznewsletter/robinson_user' )}" />
    </div>
{* DESIGN: Control bar END *}</div></div></div></div></div></div>
</div>
</form>
