{* DO NOT EDIT THIS FILE! Use an override template instead. *}
{* eZNewsletter - robinson list *}

{if is_set($warning)}
    <div class="message-warning">
        <h2>{$warning|wash}</h2>
    </div>
{/if}

<form name="robinson_edit" method="post" action={concat( '/newsletter/robinson_edit/', $robinsonlistEntry.id )|ezurl}>

<div class="context-block">
{* DESIGN: Header START *}<div class="box-header"><div class="box-tc"><div class="box-ml"><div class="box-mr"><div class="box-tl"><div class="box-tr">
<h2 class="context-title">{'Edit robinsonlist entry'|i18n( 'design/eznewsletter/robinson_edit' )}</h2>

{* DESIGN: Mainline *}<div class="header-mainline"></div>

{* DESIGN: Header END *}</div></div></div></div></div></div>

{* DESIGN: Content START *}<div class="box-ml"><div class="box-mr"><div class="box-content">

<div class="context-attributes">

<div class="block">
    
    <div class="element">
        <label>{'List'|i18n( 'design/eznewsletter/robinson_edit' )}</label>
        <select name="RobinsonlistEntry_Global" size="4">
            {foreach $global_map as $value => $name}
                <option value="{$value}" {cond( eq($value,$robinsonlistEntry.global), 'selected="selected"', '' )}">{$name|wash}</a></option>
            {/foreach}
	</select>
    </div>

    <div class="element">
            <label>{'Type of data:'|i18n( 'design/eznewsletter/robinson_edit' )}</label>
            <select name="RobinsonlistEntry_Type" size="3">
                {foreach $type_map as $value => $name}
            	    <option value="{$value}" {cond( eq($value,$robinsonlistEntry.type), 'selected="selected"', '' )}">{$name|wash}</a></option>
                {/foreach}
            </select>
    </div>
</div>

    {* Value. *}
    <div class="block">
        <label>{"Email address or mobile number"|i18n( 'design/eznewsletter/robinson_edit' )}</label>
        <input class="halfbox" id="RobinsonlistEntry_Value" type="text" name="RobinsonlistEntry_Value" value="{$robinsonlistEntry.value|wash}" title="{'Email address or mobile phone number.'|i18n( 'design/eznewsletter/robinson_edit' )}" />
    </div>

{* DESIGN: Content END *}</div></div></div>


    {* Buttons. *}
    <div class="controlbar">
{* DESIGN: Control bar START *}<div class="box-bc"><div class="box-ml"><div class="box-mr"><div class="box-tc"><div class="box-bl"><div class="box-br">
    <div class="block">
        <input class="button" type="submit" name="StoreButton" value="{'Ok'|i18n( 'design/eznewsletter/robinson_edit' )}" title="{'Apply the changes and return to opt-out list.'|i18n( 'design/eznewsletter/robinson_edit' )}" />
        <input class="button" type="submit" name="CancelButton" value="{'Cancel'|i18n( 'design/eznewsletter/robinson_edit' )}" title="{'Cancel the changes and return to the opt-out list.'|i18n( 'design/eznewsletter/robinson_edit' )}" />
    </div>
{* DESIGN: Control bar END *}</div></div></div></div></div></div>
</div>
</form>			
