{* DO NOT EDIT THIS FILE! Use an override template instead. *}
{* eZNewsletter - robinson list *}
{*def $base_uri2=concat( 'newsletter/robinson_show', '/(offset)/', $view_parameters.offset, '/(statusFilter)/', $view_parameters.statusFilter )*}
{def $base_uri='newsletter/robinson_show'}

<div class="context-block">
{* DESIGN: Header START *}<div class="box-header"><div class="box-tc"><div class="box-ml"><div class="box-mr"><div class="box-tl"><div class="box-tr">
<h2 class="context-title">{'Opt-out list'|i18n( 'design/eznewsletter/robinson_show' )|wash}</h2>

{* DESIGN: Mainline *}<div class="header-mainline"></div>

{* DESIGN: Header END *}</div></div></div></div></div></div>

{* DESIGN: Content START *}<div class="box-ml"><div class="box-mr"><div class="box-content">

<div class="context-attributes">
    {* Name. *}
    <div colass="block">
    <div class="element">
    
    <div class="block">
        <label>{"Filter list by local/global entries:"|i18n( 'design/eznewsletter/robinson_show' )}</label>
    </div>
    
    </div>
    </div>

<form name="robinson_list" method="post" action={concat( '/newsletter/robinson_show' )|ezurl}>

            <div class="element">
            <label>{'List type:'|i18n( 'design/eznewsletter/robinson_show' )}</label>
            <select name="statusFilter[]" multiple="multiple" size="4">
                <option value="-1" {cond( $statusFilter|contains( '-1' ), 'selected="selected"', '' )}>{'Show all'|i18n( 'design/eznewsletter/robinson_show' )}</option>
                {foreach $status_map as $value => $name}
                    <option value="{$value}" {cond( $statusFilter|contains( $value ), 'selected="selected"', '' )} >{$name|wash}</a>
                {/foreach}
            </select>
            <input class="button" type="submit" name="SubmitFilter" value="{'Filter'|i18n( 'design/eznewsletter/robinson_show' )}" title="{'Filter  subscription list.'|i18n( 'design/eznewsletter/robinson_show' )}" />
            </div>
    </div>
    <div class="break"></div>
</div>

{* DESIGN: Header START *}<div class="box-header"><div class="box-tc"><div class="box-ml"><div class="box-mr"><div class="box-tl"><div class="box-tr">
<h2 class="context-title">{'Opt-out lists ( %number_emails Emails / %number_mobile Mobile numbers )'|i18n( 'eznewsletter',, hash( '%number_emails', $robinsonlistCount_Email, '%number_mobile', $robinsonlistCount_Mobile) )|wash}</h2>

{* DESIGN: Subline *}<div class="header-subline"></div>
{* DESIGN: Header END *}</div></div></div></div></div></div>

{* DESIGN:  START *}<div class="box-ml"><div class="box-mr"><div class="box-content">
<div class="context-attributes">

{* Subscriber list *}
<div class="context-toolbar">
<div class="block">
<div class="left">
<p>

{switch match=$limit}
    {case match=25}
        <a href={'/user/preferences/set/admin_list_limit/1'|ezurl} title="{'Show 10 items per page.'|i18n( 'design/admin/node/view/full' )}">10</a>
        <span class="current">25</span>
        <a href={'/user/preferences/set/admin_list_limit/3'|ezurl} title="{'Show 50 items per page.'|i18n( 'design/admin/node/view/full' )}">50</a>
    {/case}
    {case match=50}
        <a href={'/user/preferences/set/admin_list_limit/1'|ezurl} title="{'Show 10 items per page.'|i18n( 'design/admin/node/view/full' )}">10</a>
        <a href={'/user/preferences/set/admin_list_limit/2'|ezurl} title="{'Show 25 items per page.'|i18n( 'design/admin/node/view/full' )}">25</a>
        <span class="current">50</span>
    {/case}
    {case}
        <span class="current">10</span>
        <a href={'/user/preferences/set/admin_list_limit/2'|ezurl} title="{'Show 25 items per page.'|i18n( 'design/admin/node/view/full' )}">25</a>
        <a href={'/user/preferences/set/admin_list_limit/3'|ezurl} title="{'Show 50 items per page.'|i18n( 'design/admin/node/view/full' )}">50</a>
    {/case}
{/switch}
</p>
</div>
<div class="break"></div>
</div>
</div>

<div class="doubleTable">
{*table email*}

{* Subscription list table. *}
<div class="leftTable">
<table class="list" cellspacing="0">
<tr>
    <th class="tight"><img src={'toggle-button-16x16.gif'|ezimage} alt="{'Invert selection'|i18n( 'design/eznewsletter/robinson_show' )}" title="{'Invert selection'|i18n( 'design/eznewsletter/robinson_show' )}" onclick="ezjs_toggleCheckboxes( document.robinson_list, 'EmailIDArray[]' ); return false;" /></th>
    <th>{'Email'|i18n( 'design/eznewsletter/robinson_show' )}</th>
    <th>{'Status'|i18n( 'design/eznewsletter/robinson_show' )}</th>
    <th></th>
</tr>
{foreach $robinsonlist_Email as $entry
         sequence array( bglight, bgdark ) as $seq}

<tr class="{$seq}">
    <td><input type="checkbox" name="EmailIDArray[]" value="{$entry.id}" title="{'Select entry for removal.'|i18n( 'design/eznewsletter/robinson_show' )}" /></td>
    <td><a href="mailto:{$entry.value|wash}">{$entry.value|wash}</a></td>
     <td>{$entry.global_map[$entry.global]|wash}</td>
    <td>
<a href={concat( '/newsletter/robinson_edit/', $entry.id )|ezurl}><img src={'edit.gif'|ezimage} alt="{'Edit'|i18n( 'design/eznewsletter/robinson_show' )}" title="{'Edit entry.'|i18n( 'design/eznewsletter/robinson_show' )|wash}" /></a>
</td>
</tr>
{/foreach}
</table>
</div>

{*table email end*}
{*table mobile*}

{* Subscription list table. *}
<div class="rightTable">
<table class="list" cellspacing="0">
<tr>
    <th class="tight"><img src={'toggle-button-16x16.gif'|ezimage} alt="{'Invert selection.'|i18n( 'design/eznewsletter/robinson_show' )}" title="{'Invert selection.'|i18n( 'design/eznewsletter/robinson_show' )}" onclick="ezjs_toggleCheckboxes( document.robinson_list, 'MobileIDArray[]' ); return false;" /></th>
    <th>{'Mobile'|i18n( 'design/eznewsletter/robinson_show' )}</th>
    <th>{'Status'|i18n( 'design/eznewsletter/robinson_show' )}</th>
    <th></th>
</tr>
{foreach $robinsonlist_Mobile as $entry
         sequence array( bglight, bgdark ) as $seq}

<tr class="{$seq}">
    <td><input type="checkbox" name="MobileIDArray[]" value="{$entry.id}" title="{'Select entry for removal'|i18n( 'design/eznewsletter/robinson_show' )}" /></td>
    <td>{$entry.value|wash}</a></td>
     <td>{$entry.global_map[$entry.global]|wash}</td>
    <td>
<a href={concat( '/newsletter/robinson_edit/', $entry.id )|ezurl}><img src={'edit.gif'|ezimage} alt="{'Edit'|i18n( 'design/eznewsletter/robinson_show' )}" title="{'Edit entry.'|i18n( 'design/eznewsletter/robinson_show' )|wash}" /></a>
</td>
</tr>
{/foreach}
</table>
</div>

{*table mobile end*}
</div>
<div class="doubleTableClean"></div>

{if gt($robinsonlistCount_Email,$robinsonlistCount_Mobile)}
    {def $countEntrys=$robinsonlistCount_Email}
{else}
    {def $countEntrys=$robinsonlistCount_Mobile}
{/if}

{* Navigator. *}
<div class="context-toolbar">
    {include name=navigator
         uri='design:navigator/google.tpl'
         page_uri=$base_uri
         item_count=$countEntrys
         view_parameters=$view_parameters
         item_limit=$limit}
</div>

{* DESIGN: Table END *}</div></div></div>

    <div class="controlbar">
{* DESIGN: Control bar START *}<div class="box-bc"><div class="box-ml"><div class="box-mr"><div class="box-tc"><div class="box-bl"><div class="box-br">

<div class="left">
    <input class="button" type="submit" name="RemoveRobinsonlistEntryButton" value="{'Remove selected'|i18n( 'design/eznewsletter/robinson_show' )}" title="{'Remove selected entry.'|i18n( 'design/eznewsletter/robinson_show' )}" />
    <input class="button" type="submit" name="CreateRobinsonlistEntryButton" value="{'New entry'|i18n( 'design/eznewsletter/robinson_show' )}" title="{'Create a new entry.'|i18n( 'design/eznewsletter/robinson_show' )}" />

</form>

    <form name="import" method="GET" action={concat( 'newsletter/robinson_import/')|ezurl} style="display:inline">
            <input class="button" type="submit" value="{'Import from file'|i18n( 'design/eznewsletter/robinson_show' )}" title="{'Import entries from file.'|i18n( 'design/eznewsletter/robinson_show' )}" />
    </form>
</div>

{* DESIGN: Control bar END *}</div></div></div></div></div></div>
    </div>

{* DESIGN: Content END *}</div></div></div>
