{* DO NOT EDIT THIS FILE! Use an override template instead. *}
{def $base_uri=concat( '/newsletter/unsubscribe/', $subscriptionList.url_alias )}

{if $warning}
    <div class="message-warning">
        <h2>{$warning|wash}</h2>
    </div>
{/if}

<form name="subscription_list" method="post" action={$base_uri|ezurl}>

    {* Email. *}
    <div class="block">
        <label>{"Email"|i18n( 'design/eznewsletter/unsubscribe' )}:</label>
        <input class="halfbox" id="subscriptionEmail" type="text" name="Email" value="{cond( is_set( $user ), $user.email, $email)|wash}" title="{'Email of the subscriber.'|i18n( 'design/eznewsletter/unsubscribe' )}"
               {cond( is_set( $user ), 'readonly="readonly"', '')} />
    </div>

    {if $subscriptionList.require_password}
        {* Password. *}
        <div class="block">
            <label>{"Password"|i18n( 'design/eznewsletter/unsubscribe' )}:</label>
            <input name="Password" size="25" type="password" value="password" {cond( is_set( $user ), 'readonly="readonly"', '' )} />
        </div>
    {/if}

    <div class="block">
        <input class="button" type="submit" name="StoreButton" value="{'Unsubscribe'|i18n( 'design/eznewsletter/unsubscribe' )}" title="{'Unsubscribe subscription'|i18n( 'design/eznewsletter/unsubscribe' )}" />
        <input class="button" type="submit" name="CancelButton" value="{'Cancel'|i18n( 'design/eznewsletter/unsubscribe' )}" title="{'Cancel and discard.'|i18n( 'design/eznewsletter/unsubscribe' )}" />
    </div>

</form>
