{* DO NOT EDIT THIS FILE! Use an override template instead. *}
{* eZNewsletter - edit newslettertype *}

<div class="box">
<div class="tl">
<div class="tr">
<div class="br">
<div class="bl">
<div class="box-content float-break">

<form method="post" action={concat( '/newsletter/user_settings/', $hash)|ezurl}>
<h2>{'Please enter your password'|i18n( 'design/eznewsletter/user_settings_password' )}</h2>
<input type="Password" name="Password" /><br />
<input class="button" type="submit" name="Submit" value="{'Submit'|i18n( 'design/eznewsletter/user_settings_password' )}" title="{'Update settings'|i18n( 'design/eznewsletter/user_settings_password' )}" />

</form>

</div></div></div>
</div></div></div>
