{* DO NOT EDIT THIS FILE! Use an override template instead. *}
{* eZNewsletter - edit newslettertype *}
<form method="post" action={concat('/newsletter/modify_subscription/',$hash)|ezurl}>

<input type="hidden" name="original_email" value="{$userData.email}" />

{include uri="design:eznewsletter/user_settings_profile.tpl"}

{include uri="design:eznewsletter/user_addsubscription.tpl"}

{* Subscription template *}<div class="context-block">
<div class="box-header"><div class="box-tc"><div class="box-ml"><div class="box-mr"><div class="box-tl"><div class="box-tr">
<h1 class="context-title">{'Subscriptions'|i18n( 'design/eznewsletter/edit_subscription_list' )}</h1>
<div class="header-mainline"></div>
</div></div></div></div></div></div>
<div class="box-bc"><div class="box-ml"><div class="box-mr"><div class="box-bl"><div class="box-br"><div class="box-content">
<div class="break"></div>


{* Newsletter type table. *}
<table class="list" cellspacing="0">
<tr>
    <th>{'Name'|i18n( 'design/eznewsletter/edit_subscription_list' )}</th>
    <th>{'Status'|i18n( 'design/eznewsletter/edit_subscription_list' )}</th>
</tr>
{if count($subscriptionList)|lt(1)}
<tr><td>&nbsp;</td><td>{'No subscriptions available'|i18n( 'design/eznewsletter/edit_subscription_list' )}</td></tr>
{else}
    {foreach $subscriptionList as $subscription
             sequence array( bglight, bgdark ) as $seq}
        <tr class="{$seq}">
        <td>{$subscription.subscription_list.name|wash}</td>
        <td>
        {if $allowedStatusList|contains( $subscription.status )}
            <select name="Status_{$subscription.id}" class="halfbox">
            {foreach $allowedStatusList as $allowedStatus}
                <option value="{$allowedStatus}" {cond( $subscription.status|eq( $allowedStatus ), 'selected="selected"', '' )}>{$statusNameMap[$allowedStatus]|wash}</option>
            {/foreach}
            </select>
        {else}
            {$statusNameMap[$subscription.status]|wash}
        {/if}
        </td>
        </tr>
    {/foreach}
{/if}
</table>


{* DESIGN: Content END *}</div></div></div>

{* Buttons. *}
<div class="controlbar">
{* DESIGN: Control bar START *}<div class="halfbox-bc"><div class="halfbox-ml"><div class="halfbox-mr"><div class="halfbox-tc"><div class="halfbox-bl"><div class="halfbox-br">
<div class="block">
    <input class="button" type="submit" name="UpdateSubscriptions" value="{'Update'|i18n( 'design/eznewsletter/edit_subscription_list' )}" title="{'Update settings.'|i18n( 'design/eznewsletter/edit_subscription_list' )}" 
{if is_set($newUser)}
disabled="disabled"
{/if}
/>
</div>
{* DESIGN: Control bar END *}</div></div></div></div></div></div>
</div>
</div>

<div class="break"></div><div class="break"></div><div class="break"></div>
</div></div></div></div></div></div> 
</div>

</form>
 
